### ISSUE TITLE
TTS WAV file is not playing on android and Safari

### ISSUE THREAD

**Issue by playground** [watson-developer-cloud/speech-javascript-sdk#56] opened 2017-09-04 15:00 UTC
@nfriedly I have put together this web app that works in Chrome, FF and Edge for TTS/STT but TTS fails on Android.  Seems like TTS/STT both fail for Safari.

Here is the link to the web app https://web-weather-ai-dev.os-app.dev-001.wc.weather.com/

Thanks

**Comment by germanattanasio** [comment] 2017-09-04 21:00
Which version of Safari are you using? 10.0.1 had an issue with WebSockets. It was fixed in the latest release.

Regarding Android, try to use `.mp3` instead of `.wav`.

**Comment by nfriedly** [comment] 2017-09-05 14:13
Confirmed in Chrome 60 on Android. I think Chrome may have implemented the same "audio playback must be in direct response to a user action" rule as mobile Safari - [this example](https://watson-speech.mybluemix.net/file-url.html) works, but none of the others seem to.

For Safari, no *current* release allows microphone access, but the previews of the next release (due out soon) do. I just tested it in Safari Technology Preview, and STT worked, but TTS was blocked, perhaps it has the same limitation as mobile Safari (and, apparently, mobile Chrome).

I think there is probably a way to work around the playback limitations - basically have audio continuously "playing" but just play silence most of the time - but that will take a fair amount of work to implement, so I can't commit to it being done any time soon.

FWIW, it works on Firefox 55 on Android.

**Comment by playground** [comment] 2017-09-05 14:31
@germanattanasio Safari Version 10.1.2 (12603.3.8)

@nfriedly what would you recommend for the interim solution?

**Comment by nfriedly** [comment] 2017-09-05 14:45
For desktop support, you just have to ask users to use any browser except Safari (until the next release).

For mobile, I would recommend native apps for the time being, especially if you want iOS support. We have [Java](https://github.com/watson-developer-cloud/java-sdk) & [Swift](https://github.com/watson-developer-cloud/swift-sdk) SDKs to help there.

**Comment by playground** [comment] 2017-09-05 14:47
I was trying to avoid native app completely and go with PWA all the way :-)

**Comment by nfriedly** [comment] 2017-09-05 14:53
Yea, I know; think that Apple will allow microphone access in the next release of iOS safari, in addition to desktop safari. So it may be possible in a few weeks. If you feel like gambling on that, and putting in the work to make TTS playback work as a single continuous stream, I'd be happy to provide a little guidance and accept a pull request.

**Comment by playground** [comment] 2017-09-12 23:01
@germanattanasio how to output .mp3?

**Comment by germanattanasio** [comment] 2017-09-13 00:32
Look at the docukentation. I think you need to send an accept parameter

**Comment by nfriedly** [comment] 2017-09-13 19:26
Yep, see http://watson-developer-cloud.github.io/speech-javascript-sdk/master/module-watson-speech_text-to-speech_synthesize.html

Set it to `audio/mp3` to force mp3 format: 

```js
WatsonSpeech.TextToSpeech.synthesize({
  text: "Testing 1 2 3",
  token: token,
  accept: 'audio/mp3'
});
```

Note that browsers automatically set an `Accept` header, so in theory overriding it shouldn't be necessary. But it's still available in case it's needed.

**Comment by fukuda34** [comment] 2017-09-23 02:55
iOS 11 was released and allows microphone access for Safari. I tried the streaming example below, but it doesn't work.
https://watson-speech.mybluemix.net/microphone-streaming.html
Should it work or not? Could you please anyone teach me?

**Comment by playground** [comment] 2017-09-23 13:05
@nfriedly I have tried outputing mp3 but still not working for Android.

**Comment by nfriedly** [comment] 2017-09-25 18:04
@fukuda34 I'm not sure, I haven't had the opportunity to test things on iOS 11 yet. 

@playground What about this example: https://watson-speech.mybluemix.net/file-url.html - I think the condition might be that it must be in *direct* response to a user action (so you can only play when they click/tap, and you must have the token pre-loaded.) 

If I recall correctly, your use-case involved playing back audio in response to user microphone input. I believe chrome and safari both block this now. It appears to be an intentional limitation, but since it's breaking your real-world use-case, I'd encourage you to file a bug on their respective issue trackers: 

* Chromium (Chrome): http://dev.chromium.org/for-testers/bug-reporting-guidelines
* Webkit (Safari): https://webkit.org/reporting-bugs/

Please leave links here to the bugs if you do file them.

As mentioned [previously](https://github.com/watson-developer-cloud/speech-javascript-sdk/issues/56#issuecomment-327188265), it may be possible to work around this in code, but it's not an insignificant amount of work.

**Comment by germanattanasio** [comment] 2019-07-26 17:40
- [x] Safari mobile in an iPhone X
- [x] Safari app 12.1.2 
- [x] Chrome mobile in Pixel 2

It looks like browsers were updated since we last check this.
What else should I test before I close this?

**Closed** 2019-09-11 20:36 UTC
